#!/bin/bash

flag=0;
if [[ $1 == *.cpp ]]
then
    echo "compiling $1 ................."
    g++ -O2 -w -std=c++11 -o ${1%.*}.out  $1;
    flag=1;
elif [[ $1 == *.c ]]
then
    echo "compiling $1 ................."
    gcc -O2 -w -o ${1%.*}.out $1;
    flag=1;
elif [[ $1 == *.java ]]
then
    echo "compiling $1.................."
    javac $1
    flag=2;     
else
    
    echo "Please compile only .c or .cpp files"
    exit 0;
fi


if [ $? -eq 0 ]
then
    echo "compile Successfully."
    echo "Output file => ${1%.*}.out"
    if [[ $# == 1 ]]
    then
        if [[ $flag == 1 ]]
        then
            ./${1%.*}.out
        elif [[ $flag == 2 ]]
        then
            java ${1%.*}
        fi        
    elif [[ $# == 2 ]]
    then
        echo "input file => $2"
        if [[ $flag == 1 ]]
        then
            ./${1%.*}.out < $2
        elif [[ $flag == 2 ]]
        then
            java ${1%.*} < $2
        fi    
    elif [[ $# == 3 ]]
    then
        echo "input file => $2"
        echo "output file => $3"
        if [[ $flag == 1 ]]
        then 
           ./${1%.*}.out <$2 >$3
        elif [[ $flag == 2 ]]
        then
            java ${1%.*} <$2 >$3   
        fi   
    fi
else
    echo "Compilation Error"
fi

